### ISSUE TITLE
Create Form Backend

### ISSUE THREAD

**Issue by karmelyoei** [GSG-K3/360HMR#37]
The manager will pick the questions or adding new questions for creating the form of the review on this issue:

1. Build a basic Front end

1. Connect the backend with the front end through the proxy

1. using Axios to send requests and receive a response from the front to back

1. write a query to insert the new questions into the db 

1. receiving a response with the related message for a successful operation

**Comment by karmelyoei** [comment]
![project](https://user-images.githubusercontent.com/39573452/86889394-54812080-c104-11ea-9df5-08ff82385cb3.png)

**Comment by karmelyoei** [comment]
I have got an error "self-signed certificate error in node js with db" 
```
 Error: self signed certificate
[0]     at TLSSocket.onConnectSecure (_tls_wrap.js:1498:34)
[0]     at TLSSocket.emit (events.js:315:20)
[0]     at TLSSocket._finishInit (_tls_wrap.js:940:8)
[0]     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:698:12) {
[0]   code: 'DEPTH_ZERO_SELF_SIGNED_CERT'
[0] }
```

**Comment by karmelyoei** [comment]
I solved it with adding 

```js
	ssl: { rejectUnauthorized: false }
```
into db_connection.js file

**Comment by karmelyoei** [comment]
Done!
